### ISSUE TITLE
Add RTTM capability to exports sub-module

### ISSUE THREAD

**Issue by damian-romero** [clulab/lives#9]
**Description**

- [DOVER-lap](https://github.com/desh2608/dover-lap) is a system for turn diarisation IRR and for combining two or more annotator's diarization hypotheses
- DOVER-lap uses the [RTTM file type](https://github.com/nryant/dscore#rttm)
- We want to add RTTM file type support to the `exports` sub-module
- We need to be able to create joint and separate files for DOVER-lap testing for A) Overlapping turns, B) Non-overlapping turns, and C) both. See [this issue](https://github.com/desh2608/dover-lap/issues/2) for why.

**Implementation**

Implement in `json_parser.py` as:

```
    parser.add_argument("-rttm", "--diarisation-rttm", action="store_true",
                        help='Creates Rich Transcription Time Marked (RTTM) files from LabelStudio exports\
                           inside ../output/.')
```

This would create three files for each interview:

- [interview-id]_overlapping.rttm
- [interview-id]_non_overlapping.rttm
- [interview-id]_combined.rttm

**Steps**

- [x] Add turn length information #11 
- [x] Add turn overlapping information #11
- [x] Add rttm file support #12
- [ ] Manlually check overlapped turns in `turn_diarisation.csv` against LabelStudio
- [ ] Check well-formedness of RTTM files using: https://github.com/nryant/dscore#rttm
